from datetime import date, datetime
from typing import Protocol


class MarketCalendar(Protocol):
    """거래일·세션시각 판정. 내부에 '현재 시각'을 두지 않아 결정적."""

    def is_trading_day(self, d: date) -> bool: ...
    def next_trading_day(self, d: date) -> date: ...
    def previous_trading_day(self, d: date) -> date: ...
    def session_times(self, d: date) -> tuple[datetime, datetime] | None: ...
    def is_open(self, dt: datetime) -> bool: ...
