from typing import Protocol
from ohmystock.paper.account import PaperAccount


class PaperStore(Protocol):
    """페이퍼 계좌 영속 저장소. SQLite 등으로 구현."""
    def initialize(self, account: PaperAccount) -> None: ...
    def load_account(self) -> PaperAccount | None: ...
    def save_account(self, account: PaperAccount) -> None: ...
    def load_positions(self) -> dict[str, float]: ...
    def save_positions(self, shares: dict[str, float]) -> None: ...
    def append_snapshot(self, date: str, equity: float, cash: float) -> None: ...
    def append_trades(self, date: str, orders: list[dict]) -> None: ...
    def snapshots(self) -> list[dict]: ...
    def trades(self) -> list[dict]: ...
