// Curated catalog of well-known US-listed stocks and ETFs.
// Used by the symbol picker for search + autocomplete and to resolve
// human-friendly names for tickers (including those pulled from history).

export interface SymbolInfo {
  symbol: string
  name: string
}

export const SYMBOLS: SymbolInfo[] = [
  // Technology -----------------------------------------------------------
  { symbol: 'AAPL', name: 'Apple Inc.' },
  { symbol: 'MSFT', name: 'Microsoft Corporation' },
  { symbol: 'GOOGL', name: 'Alphabet Inc. (Class A)' },
  { symbol: 'GOOG', name: 'Alphabet Inc. (Class C)' },
  { symbol: 'AMZN', name: 'Amazon.com, Inc.' },
  { symbol: 'META', name: 'Meta Platforms, Inc.' },
  { symbol: 'NVDA', name: 'NVIDIA Corporation' },
  { symbol: 'TSLA', name: 'Tesla, Inc.' },
  { symbol: 'AMD', name: 'Advanced Micro Devices, Inc.' },
  { symbol: 'NFLX', name: 'Netflix, Inc.' },
  { symbol: 'INTC', name: 'Intel Corporation' },
  { symbol: 'CRM', name: 'Salesforce, Inc.' },
  { symbol: 'ORCL', name: 'Oracle Corporation' },
  { symbol: 'ADBE', name: 'Adobe Inc.' },
  { symbol: 'AVGO', name: 'Broadcom Inc.' },
  { symbol: 'QCOM', name: 'QUALCOMM Incorporated' },
  { symbol: 'CSCO', name: 'Cisco Systems, Inc.' },
  { symbol: 'IBM', name: 'International Business Machines Corporation' },
  { symbol: 'TXN', name: 'Texas Instruments Incorporated' },
  { symbol: 'MU', name: 'Micron Technology, Inc.' },
  { symbol: 'AMAT', name: 'Applied Materials, Inc.' },
  { symbol: 'LRCX', name: 'Lam Research Corporation' },
  { symbol: 'ADI', name: 'Analog Devices, Inc.' },
  { symbol: 'NOW', name: 'ServiceNow, Inc.' },
  { symbol: 'INTU', name: 'Intuit Inc.' },
  { symbol: 'SNOW', name: 'Snowflake Inc.' },
  { symbol: 'PLTR', name: 'Palantir Technologies Inc.' },
  { symbol: 'PANW', name: 'Palo Alto Networks, Inc.' },
  { symbol: 'CRWD', name: 'CrowdStrike Holdings, Inc.' },
  { symbol: 'DDOG', name: 'Datadog, Inc.' },
  { symbol: 'NET', name: 'Cloudflare, Inc.' },
  { symbol: 'ZS', name: 'Zscaler, Inc.' },
  { symbol: 'TEAM', name: 'Atlassian Corporation' },
  { symbol: 'WDAY', name: 'Workday, Inc.' },
  { symbol: 'PINS', name: 'Pinterest, Inc.' },
  { symbol: 'SNAP', name: 'Snap Inc.' },
  { symbol: 'SPOT', name: 'Spotify Technology S.A.' },
  { symbol: 'ROKU', name: 'Roku, Inc.' },
  { symbol: 'DELL', name: 'Dell Technologies Inc.' },
  { symbol: 'HPQ', name: 'HP Inc.' },
  { symbol: 'MRVL', name: 'Marvell Technology, Inc.' },
  { symbol: 'ON', name: 'ON Semiconductor Corporation' },

  // Communications / Media -----------------------------------------------
  { symbol: 'DIS', name: 'The Walt Disney Company' },
  { symbol: 'CMCSA', name: 'Comcast Corporation' },
  { symbol: 'T', name: 'AT&T Inc.' },
  { symbol: 'VZ', name: 'Verizon Communications Inc.' },
  { symbol: 'TMUS', name: 'T-Mobile US, Inc.' },
  { symbol: 'WBD', name: 'Warner Bros. Discovery, Inc.' },
  { symbol: 'EA', name: 'Electronic Arts Inc.' },
  { symbol: 'TTWO', name: 'Take-Two Interactive Software, Inc.' },

  // Consumer -------------------------------------------------------------
  { symbol: 'KO', name: 'The Coca-Cola Company' },
  { symbol: 'PEP', name: 'PepsiCo, Inc.' },
  { symbol: 'MCD', name: "McDonald's Corporation" },
  { symbol: 'SBUX', name: 'Starbucks Corporation' },
  { symbol: 'NKE', name: 'NIKE, Inc.' },
  { symbol: 'WMT', name: 'Walmart Inc.' },
  { symbol: 'COST', name: 'Costco Wholesale Corporation' },
  { symbol: 'HD', name: 'The Home Depot, Inc.' },
  { symbol: 'LOW', name: "Lowe's Companies, Inc." },
  { symbol: 'TGT', name: 'Target Corporation' },
  { symbol: 'PG', name: 'The Procter & Gamble Company' },
  { symbol: 'CL', name: 'Colgate-Palmolive Company' },
  { symbol: 'MDLZ', name: 'Mondelez International, Inc.' },
  { symbol: 'KHC', name: 'The Kraft Heinz Company' },
  { symbol: 'PM', name: 'Philip Morris International Inc.' },
  { symbol: 'MO', name: 'Altria Group, Inc.' },
  { symbol: 'EL', name: 'The Estée Lauder Companies Inc.' },
  { symbol: 'YUM', name: 'Yum! Brands, Inc.' },
  { symbol: 'CMG', name: 'Chipotle Mexican Grill, Inc.' },
  { symbol: 'LULU', name: 'Lululemon Athletica Inc.' },
  { symbol: 'BKNG', name: 'Booking Holdings Inc.' },
  { symbol: 'MAR', name: 'Marriott International, Inc.' },
  { symbol: 'ABNB', name: 'Airbnb, Inc.' },
  { symbol: 'UBER', name: 'Uber Technologies, Inc.' },
  { symbol: 'LYFT', name: 'Lyft, Inc.' },
  { symbol: 'DASH', name: 'DoorDash, Inc.' },
  { symbol: 'SHOP', name: 'Shopify Inc.' },
  { symbol: 'ETSY', name: 'Etsy, Inc.' },
  { symbol: 'EBAY', name: 'eBay Inc.' },
  { symbol: 'F', name: 'Ford Motor Company' },
  { symbol: 'GM', name: 'General Motors Company' },
  { symbol: 'RIVN', name: 'Rivian Automotive, Inc.' },
  { symbol: 'LCID', name: 'Lucid Group, Inc.' },

  // Financials -----------------------------------------------------------
  { symbol: 'JPM', name: 'JPMorgan Chase & Co.' },
  { symbol: 'BAC', name: 'Bank of America Corporation' },
  { symbol: 'WFC', name: 'Wells Fargo & Company' },
  { symbol: 'GS', name: 'The Goldman Sachs Group, Inc.' },
  { symbol: 'MS', name: 'Morgan Stanley' },
  { symbol: 'C', name: 'Citigroup Inc.' },
  { symbol: 'USB', name: 'U.S. Bancorp' },
  { symbol: 'PNC', name: 'The PNC Financial Services Group, Inc.' },
  { symbol: 'SCHW', name: 'The Charles Schwab Corporation' },
  { symbol: 'BLK', name: 'BlackRock, Inc.' },
  { symbol: 'AXP', name: 'American Express Company' },
  { symbol: 'V', name: 'Visa Inc.' },
  { symbol: 'MA', name: 'Mastercard Incorporated' },
  { symbol: 'PYPL', name: 'PayPal Holdings, Inc.' },
  { symbol: 'SQ', name: 'Block, Inc.' },
  { symbol: 'COIN', name: 'Coinbase Global, Inc.' },
  { symbol: 'BRK-B', name: 'Berkshire Hathaway Inc. (Class B)' },
  { symbol: 'BX', name: 'Blackstone Inc.' },
  { symbol: 'SPGI', name: 'S&P Global Inc.' },
  { symbol: 'CB', name: 'Chubb Limited' },
  { symbol: 'MMC', name: 'Marsh & McLennan Companies, Inc.' },

  // Healthcare -----------------------------------------------------------
  { symbol: 'JNJ', name: 'Johnson & Johnson' },
  { symbol: 'PFE', name: 'Pfizer Inc.' },
  { symbol: 'MRK', name: 'Merck & Co., Inc.' },
  { symbol: 'ABBV', name: 'AbbVie Inc.' },
  { symbol: 'UNH', name: 'UnitedHealth Group Incorporated' },
  { symbol: 'LLY', name: 'Eli Lilly and Company' },
  { symbol: 'TMO', name: 'Thermo Fisher Scientific Inc.' },
  { symbol: 'ABT', name: 'Abbott Laboratories' },
  { symbol: 'DHR', name: 'Danaher Corporation' },
  { symbol: 'BMY', name: 'Bristol-Myers Squibb Company' },
  { symbol: 'AMGN', name: 'Amgen Inc.' },
  { symbol: 'GILD', name: 'Gilead Sciences, Inc.' },
  { symbol: 'CVS', name: 'CVS Health Corporation' },
  { symbol: 'MDT', name: 'Medtronic plc' },
  { symbol: 'ISRG', name: 'Intuitive Surgical, Inc.' },
  { symbol: 'VRTX', name: 'Vertex Pharmaceuticals Incorporated' },
  { symbol: 'REGN', name: 'Regeneron Pharmaceuticals, Inc.' },
  { symbol: 'MRNA', name: 'Moderna, Inc.' },
  { symbol: 'ZTS', name: 'Zoetis Inc.' },

  // Energy ---------------------------------------------------------------
  { symbol: 'XOM', name: 'Exxon Mobil Corporation' },
  { symbol: 'CVX', name: 'Chevron Corporation' },
  { symbol: 'COP', name: 'ConocoPhillips' },
  { symbol: 'SLB', name: 'Schlumberger Limited' },
  { symbol: 'EOG', name: 'EOG Resources, Inc.' },
  { symbol: 'OXY', name: 'Occidental Petroleum Corporation' },
  { symbol: 'PSX', name: 'Phillips 66' },
  { symbol: 'MPC', name: 'Marathon Petroleum Corporation' },
  { symbol: 'KMI', name: 'Kinder Morgan, Inc.' },
  { symbol: 'WMB', name: 'The Williams Companies, Inc.' },

  // Industrials ----------------------------------------------------------
  { symbol: 'BA', name: 'The Boeing Company' },
  { symbol: 'CAT', name: 'Caterpillar Inc.' },
  { symbol: 'GE', name: 'GE Aerospace' },
  { symbol: 'HON', name: 'Honeywell International Inc.' },
  { symbol: 'UPS', name: 'United Parcel Service, Inc.' },
  { symbol: 'FDX', name: 'FedEx Corporation' },
  { symbol: 'LMT', name: 'Lockheed Martin Corporation' },
  { symbol: 'RTX', name: 'RTX Corporation' },
  { symbol: 'DE', name: 'Deere & Company' },
  { symbol: 'MMM', name: '3M Company' },
  { symbol: 'GD', name: 'General Dynamics Corporation' },
  { symbol: 'NOC', name: 'Northrop Grumman Corporation' },
  { symbol: 'EMR', name: 'Emerson Electric Co.' },
  { symbol: 'CSX', name: 'CSX Corporation' },
  { symbol: 'UNP', name: 'Union Pacific Corporation' },

  // Materials / Utilities ------------------------------------------------
  { symbol: 'LIN', name: 'Linde plc' },
  { symbol: 'FCX', name: 'Freeport-McMoRan Inc.' },
  { symbol: 'NEM', name: 'Newmont Corporation' },
  { symbol: 'NEE', name: 'NextEra Energy, Inc.' },
  { symbol: 'DUK', name: 'Duke Energy Corporation' },
  { symbol: 'SO', name: 'The Southern Company' },

  // ETFs -----------------------------------------------------------------
  { symbol: 'SPY', name: 'SPDR S&P 500 ETF Trust' },
  { symbol: 'QQQ', name: 'Invesco QQQ Trust' },
  { symbol: 'DIA', name: 'SPDR Dow Jones Industrial Average ETF Trust' },
  { symbol: 'VTI', name: 'Vanguard Total Stock Market ETF' },
  { symbol: 'VOO', name: 'Vanguard S&P 500 ETF' },
  { symbol: 'IWM', name: 'iShares Russell 2000 ETF' },
  { symbol: 'VEA', name: 'Vanguard FTSE Developed Markets ETF' },
  { symbol: 'VWO', name: 'Vanguard FTSE Emerging Markets ETF' },
  { symbol: 'EFA', name: 'iShares MSCI EAFE ETF' },
  { symbol: 'AGG', name: 'iShares Core U.S. Aggregate Bond ETF' },
  { symbol: 'GLD', name: 'SPDR Gold Shares' },
  { symbol: 'TLT', name: 'iShares 20+ Year Treasury Bond ETF' },
  { symbol: 'ARKK', name: 'ARK Innovation ETF' },
  { symbol: 'XLF', name: 'Financial Select Sector SPDR Fund' },
  { symbol: 'XLE', name: 'Energy Select Sector SPDR Fund' },
  { symbol: 'XLK', name: 'Technology Select Sector SPDR Fund' },
  { symbol: 'SCHD', name: 'Schwab U.S. Dividend Equity ETF' },
]

const NAME_BY_SYMBOL: Map<string, string> = new Map(
  SYMBOLS.map((s) => [s.symbol, s.name]),
)

export function lookupName(symbol: string): string | undefined {
  return NAME_BY_SYMBOL.get(symbol.toUpperCase())
}
